# Generated by Django 2.0.6 on 2018-06-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmdb_atrr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_id', models.BigIntegerField(verbose_name='Ci_id')),
                ('prop_id', models.BigIntegerField(verbose_name='属性id')),
                ('label', models.CharField(max_length=200, verbose_name='标签')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('validator', models.SmallIntegerField(verbose_name='验证器ID')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('is_required', models.SmallIntegerField(verbose_name='是否必填')),
                ('is_search', models.SmallIntegerField(verbose_name='是否可搜索')),
                ('show_type', models.SmallIntegerField(verbose_name='字段显示方式')),
                ('is_unique', models.SmallIntegerField(verbose_name='唯一类型')),
                ('is_delete', models.SmallIntegerField(verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='cmdb_attr_entity',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('atrr_id', models.ForeignKey(null=True, on_delete=True, to='cmdb.cmdb_atrr')),
            ],
        ),
        migrations.CreateModel(
            name='cmdb_ci',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('parent_id', models.BigIntegerField(verbose_name='父Ci')),
            ],
        ),
        migrations.CreateModel(
            name='cmdb_ci_entity',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('ci_id', models.BigIntegerField(verbose_name='Ci_id')),
                ('name', models.CharField(max_length=1024, verbose_name='显示名')),
                ('unique_name', models.CharField(max_length=1024, verbose_name='唯一名')),
            ],
        ),
        migrations.AddField(
            model_name='cmdb_attr_entity',
            name='ci_entity_id',
            field=models.ForeignKey(null=True, on_delete=True, to='cmdb.cmdb_ci_entity'),
        ),
    ]
